<a href="https://colab.research.google.com/github/PatrickCalorioCarvalho/CA015ICMineracaoDeDados202601/blob/main/Aula_StrokePrediction_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('healthcare-dataset-stroke-data.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

In [4]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [5]:
df['stroke'].unique()

array([1, 0])

In [6]:
df['stroke'].value_counts()

stroke
0    4861
1     249
Name: count, dtype: int64

#### Dados faltantes

In [7]:
# Verificar todas as colunas com dados faltantes
df.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [8]:
df['bmi'].head()

0    36.6
1     NaN
2    32.5
3    34.4
4    24.0
Name: bmi, dtype: float64

In [9]:
# calcular a média da coluna bmi
media_bmi = df['bmi'].mean()
print(f"Média BMI: {media_bmi}")

Média BMI: 28.893236911794666

In [10]:
# Substituição
df['bmi'] = df['bmi'].fillna(media_bmi)
print(f"Dados faltantes: {df['bmi'].isna().sum()}")

Dados faltantes: 0

#### Reescala dos dados

In [11]:
num_cols = df.select_dtypes(include=['int64','float64']).columns.tolist()
print(num_cols)

['id', 'age', 'hypertension', 'heart_disease', 'avg_glucose_level', 'bmi', 'stroke']

In [12]:
df[num_cols].head()

,id,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
0,9046,67.0,0,1,228.69,36.600000,1
1,51676,61.0,0,0,202.21,28.893237,1
2,31112,80.0,0,1,105.92,32.500000,1
3,60182,49.0,0,0,171.23,34.400000,1
4,1665,79.0,1,0,174.12,24.000000,1

### **1. Normalização Z-Score (Padronização)**
Transforma os dados para que tenham **média 0** e **desvio padrão 1**. A fórmula usada é:

$Z = \frac{X - \mu}{\sigma}$

Onde:
- ($X$) = valor original
- ($\mu$) = média da variável
- ($\sigma$) = desvio padrão da variável


### **2. Normalização Min-Max (Escalonamento)**
Transforma os dados para um intervalo **entre 0 e 1 (ou -1 e 1)**, usando a fórmula:

$
X' = \frac{X - X_{\text{min}}}{X_{\text{max}} - X_{\text{min}}}
$

Onde:
- ($X$) = valor original
- ($X_{\text{min}}$) = menor valor da variável
- ($X_{\text{max}}$) = maior valor da variável

In [13]:
# Z-score
# remoção das colunas id e stroke
num_cols.remove('id')
num_cols.remove('stroke')

print("Antes:")
display(df[num_cols].head())

for col in num_cols:
  media = df[col].mean()
  desvio = df[col].std()
  df[col] = (df[col] - media)/desvio

print("Depois")
display(df[num_cols].head())

Antes:

    age  hypertension  heart_disease  avg_glucose_level        bmi
0  67.0             0              1             228.69  36.600000
1  61.0             0              0             202.21  28.893237
2  80.0             0              1             105.92  32.500000
3  49.0             0              0             171.23  34.400000
4  79.0             1              0             174.12  24.000000

Depois

        age  hypertension  heart_disease  avg_glucose_level           bmi
0  1.051331     -0.328570       4.184622           2.706111  1.001136e+00
1  0.785993     -0.328570      -0.238923           2.121351  4.615102e-16
2  1.626231     -0.328570       4.184622          -0.005028  4.685314e-01
3  0.255317     -0.328570      -0.238923           1.437217  7.153482e-01
4  1.582008      3.042899      -0.238923           1.501038 -6.356489e-01

#### Transformação das colunas categóricas

In [14]:
cat_cols = df.select_dtypes(include="object").columns.tolist()
print(cat_cols)

['gender', 'ever_married', 'work_type', 'Residence_type', 'smoking_status']

In [15]:
for cat in cat_cols:
  print(f"{cat}: {df[cat].unique()}")

gender: ['Male' 'Female' 'Other']
ever_married: ['Yes' 'No']
work_type: ['Private' 'Self-employed' 'Govt_job' 'children' 'Never_worked']
Residence_type: ['Urban' 'Rural']
smoking_status: ['formerly smoked' 'never smoked' 'smokes' 'Unknown']

In [16]:
# Map (colunas com até 3 categorias)
df['gender'] = df['gender'].map({'Male':0, 'Female':1, 'Other':2})
df['ever_married'] = df['ever_married'].map({'Yes':1, 'No':0})
df['Residence_type'] = df['Residence_type'].map({'Urban':1, 'Rural':0})
df[['gender','ever_married','Residence_type']].head()

   gender  ever_married  Residence_type
0       0             1               1
1       1             1               0
2       0             1               0
3       1             1               1
4       1             1               0

In [17]:
# Transformação com get_dummies (hot_encoder)
dummies = pd.get_dummies(df[['work_type','smoking_status']],
                         prefix=['work','smoke'])
dummies

,work_Govt_job,work_Never_worked,work_Private,work_Self-employed,work_children,smoke_Unknown,smoke_formerly smoked,smoke_never smoked,smoke_smokes
0,False,False,True,False,False,False,True,False,False
1,False,False,False,True,False,False,False,True,False
2,False,False,True,False,False,False,False,True,False
3,False,False,True,False,False,False,False,False,True
4,False,False,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...
5105,False,False,True,False,False,False,False,True,False
5106,False,False,False,True,False,False,False,True,False
5107,False,False,False,True,False,False,False,True,False
5108,False,False,True,False,False,False,True,False,False
5109,True,False,False,False,False,True,False,False,False

In [18]:
# Remover as colunas categóricas originais de 'df'
df = df.drop(columns=['work_type','smoking_status'])

In [19]:
df.columns

Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'Residence_type', 'avg_glucose_level', 'bmi', 'stroke'],
      dtype='object')

In [20]:
# concatenar as ciolunas dummies no dataset original
df = pd.concat([df,dummies], axis=1)

In [21]:
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,Residence_type,avg_glucose_level,bmi,stroke,work_Govt_job,work_Never_worked,work_Private,work_Self-employed,work_children,smoke_Unknown,smoke_formerly smoked,smoke_never smoked,smoke_smokes
0,9046,0,1.051331,-0.328570,4.184622,1,1,2.706111,1.001136e+00,1,False,False,True,False,False,False,True,False,False
1,51676,1,0.785993,-0.328570,-0.238923,1,0,2.121351,4.615102e-16,1,False,False,False,True,False,False,False,True,False
2,31112,0,1.626231,-0.328570,4.184622,1,0,-0.005028,4.685314e-01,1,False,False,True,False,False,False,False,True,False
3,60182,1,0.255317,-0.328570,-0.238923,1,1,1.437217,7.153482e-01,1,False,False,True,False,False,False,False,False,True
4,1665,1,1.582008,3.042899,-0.238923,1,0,1.501038,-6.356489e-01,1,False,False,False,True,False,False,False,True,False

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     5110 non-null   int64
 1   gender                 5110 non-null   int64
 2   age                    5110 non-null   float64
 3   hypertension           5110 non-null   float64
 4   heart_disease          5110 non-null   float64
 5   ever_married           5110 non-null   int64
 6   Residence_type         5110 non-null   int64
 7   avg_glucose_level      5110 non-null   float64
 8   bmi                    5110 non-null   float64
 9   stroke                 5110 non-null   int64
 10  work_Govt_job          5110 non-null   bool
 11  work_Never_worked      5110 non-null   bool
 12  work_Private           5110 non-null   bool
 13  work_Self-employed     5110 non-null   bool
 14  work_children          5110 non-null   bool
 15  smoke_Unknown          5110 non-null   bool
 16  smoke_formerly smoked  5110 non-null   bool
 17  smoke_never smoked     5110 non-null   bool
 18  smoke_smokes           5110 non-null   bool
dtypes: bool(9), float64(5), int64(5)
memory usage: 444.3 KB

#### Pré-processamento com Scikit-learn

In [23]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.impute import SimpleImputer

### Próxima aula:

* Executar todo o pré-processamento com sklearn
  * substituição de NaN com SImpleImputer
  * Normalização com MinMaxScaler ou StandardScaler
  * Transformação com OneHotEncoder

* Amostragem de dados (Treino, Teste e Validação)
* Modelo de Predição (Machine Learning)
* Vazamento de dados (Data Leakage)